### 자바 예외 종류
```
Throwable
ㄴ Error   # 컴파일러가 예외 처리 코드 여부를 검사하지 않음
ㄴ Exception
    - ClassNotFound
    - Interupted
    - ...
    ㄴ RuntimeException  # 예외 처리 코드가 없어도 컴파일 되지만, 실행중에 발생하면 프로그램이 종료됨
        - NullPointer
        - ArrayOutIndex
        - ...
```
### 다중 catch 사용시 주의점
- 다중 catch를 사용하면 예외의 종류에 따라 다른 처리를 할 수 있다.
- 다만 catch문을 여러개 사용한다고 해서 해당 catch문이 해당 예외가 일어나기만 한다면 다 해당될 것이라고 생각할 순 없다.
- catch 블록이 여러 개라 할지라도 catch 블록은 단 하나만 실행된다. try에서 제일 처음 발생한 에러에 대한 예외만 처리하기 때문이다. 
  ```java
     String [] strArr = {"100","1oo"};
          try {
              int tmp1 = Integer.parseInt(strArr[3]); // ArrayIndexOutOfBoundsException 발생
              int tmp2 = Integer.parseInt(strArr[1]); // NumberFormatException 발생
          } catch(NumberFormatException e) {
              System.out.println("NumberFormatException");
          } catch (ArrayIndexOutOfBoundsException e) {
              System.out.println("ArrayIndexOutOfBoundsException");
          } catch (Exception e) {
            System.out.println("Exception");
        }
  ```
  ```
  ArrayIndexOutOfBoundsException
  ```
- 위와 같은 문제를 해결하기 위해 코드 하나 실행시 마다 try-catch하게 구조를 바꾸면 의도대로 예외가 처리된다. 
  ```java
       String[] strArr = {"100", "1oo"};
        for (int i = 0; i <= strArr.length; i++) {
            try {
                int val = Integer.parseInt(strArr[i]);
                System.out.println(val);
            } catch (ArrayIndexOutOfBoundsException e) {
                System.out.println("ArrayIndexOutOfBoundsException");
            } catch (NumberFormatException e) {
                System.out.println("NumberFormatException");
            } catch (Exception e) {
                System.out.println("Exception");
            }
        }
  ```
  ```
  100
  NumberFormatException
  ArrayIndexOutOfBoundsException
  ```
- 처리해야 할 예외 클래스들이 상속 관계에 있을 때는, 하위 클래스 catch 블록을 먼저 작성해야 한다. : 구체적인거 먼저!
  - 예외가 발생하면 catch 블록은 위에서부터 차례대로 검사 대상이 되는데, 하위 예외도 상위 클래스 타입이므로 상위 클래스 catch 블록이 먼저 검사 대상이 되면 안된다. 
- 두 개 이상의 예외를 하나의 catch 블록으로 동일하게 예외 처리 하고 싶을 떈 예외 클래스를 기호 `|`로 연결한다. 
  - JDK 1.7 부터 가능하다.

### 예외 관련 메서드
- 에러 출력
```
1. e.getMessage() : 예외가 발생한 이유
2. e.toString() : 1 + 예외 종류 
3. e.printStackTrace : 2 + 예외가 어디서 발생했는지 추적내용 
```

### 리소스 자동 닫기 
- 리소스를 사용하다가 예외가 발생될 경우에도 안전하게 닫는 것이 중요하다. 그렇지 않으면 리소스가 불안정한 상태로 남아있게 된다.
- 원래는 finally를 사용해 리소스를 닫는 코드를 실행시켜 왔지만 `try-with-resources` 블록을 사용하면 예외 발생 여부와 관계없이 리소스를 자동으로 닫아준다. 
  1. try 괄호에 리소스를 여는 코드 작성
  2. 실행을 완료했거나 도중에 예외가 발생하면 자동으로 리소스의 close() 메소드가 호출됨
- `try-with-resources` 사용을 위해 `java.lang.AutoCloseable' 인터페이스를 구현한 뒤 `close()`를 재정의 해야 한다. 
```java
public class MyFileInputStream implements AutoCloseable {
    @Override
  public void close() throws Exception {
        
    }
}
```
```java
try(
        MyFileInputStream fis1 = new MyFileInputStream("file1.txt");
        MyFileInputStream fis2 = new MyFileInputStream("file2.txt")
        ) {
        ...
        } catch(IOException e) {
        ...   
        }
```

### 예외 떠넘기기
- 호출한 곳으로 예외를 떠넘기는 것 `throws`
- 메서드 선언부 끝에 작성한다. 떠넘길 예외 클래스를 쉼표로 구분해서 나열한다. 
- main() 메서드에서 throws 키워드를 사용하면 결국 JVM이 최종적으로 예외 처리를 하게 되고, 그 방법은 그저 콘솔에 예외 내용을 출력하는 것 ~

### 사용자 정의 예외
- 표준 라이브러리에 존재하지 않는 도메인/비즈니스적 예외를 처리 하기 위한 예외 클래스를 만드는 것 
- 사용자 정의 예외 클래스를 만들 땐, 의도에 따라 `Exception`/`RuntimeException` 의 자식클래스로 선언해야 한다. 
- 구성
  - 기본 생성자
  - 예외 메시지를 받는 생성자 (예외 메시지는 부모 생성자 매개값으로 넘김)
    - 예외 객체의 공통 메서드인 `getMessage()`의 리턴 값으로 사용하기 위해
  ```java
  public class MyException extends [Exception | RuntimeException] {
    public MyException() {}
    public MyException(String message) {
        super(message);
    }  
  }
  ```
- `throw` 키워드를 통해 의도대로 사용자 예외를 발생시켜 비즈니스 로직을 처리한다. 
  `throw new MyExceptio("예외 메시지")`
- 그리고 발생시킨 예외는 발생된 곳에서 처리될 수 있도록 `throws` 해주는 것이 관례이다.
  ```java
  public void withdraw(int money) throws InsuffientException{
    if(balabce < money) {
        throw new InsuffientException("잔고부족");
    }
    balance -= money;
  }
  ```